<?php
/**
 * Fix method: meta_description.
 *
 * Sets the SEO plugin's meta description. Suggested string is generated by
 * the Seonix backend (AI-summarised from page content, length-bounded to
 * 50–160).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Seonix_Fix_Meta_Description extends Seonix_Fix_Single_Meta {

	public function key(): string {
		return 'meta_description';
	}

	/**
	 * Static fallback (the abstract contract). The live key is chosen per
	 * active SEO plugin in resolve_meta_key().
	 */
	protected function meta_key(): string {
		$key = Seonix_SEO_Engine::post_desc_key();
		return null !== $key ? $key : '_yoast_wpseo_metadesc';
	}

	protected function target_type(): string {
		return 'post';
	}

	/**
	 * Write to the meta-description key of whichever SEO plugin is active
	 * (Yoast → _yoast_wpseo_metadesc, Rank Math → rank_math_description). When
	 * neither stores it in postmeta we can write (AIOSEO's custom table, or no
	 * SEO plugin), fail loud with 412 so the dashboard never writes meta no
	 * plugin reads.
	 *
	 * @return string|\WP_Error
	 */
	protected function resolve_meta_key() {
		$key = Seonix_SEO_Engine::post_desc_key();
		if ( null === $key ) {
			return new WP_Error(
				'no_seo_plugin',
				'No supported SEO plugin (Yoast or Rank Math) is active to store the meta description.',
				array( 'status' => 412 )
			);
		}
		return $key;
	}

	/**
	 * Advertised to the /capabilities handshake: the dashboard only offers this
	 * fix when an SEO plugin that stores the description in postmeta is active.
	 */
	public function is_available(): bool {
		return null !== Seonix_SEO_Engine::post_desc_key();
	}
}
