<?php
/**
 * Fix method: meta_description.
 *
 * Sets the SEO plugin's meta description. Suggested string is generated by
 * the Seonix backend (AI-summarised from page content, length-bounded to
 * 50–160).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Seonix_Fix_Meta_Description extends Seonix_Fix_Single_Meta {

	public function key(): string {
		return 'meta_description';
	}

	protected function meta_key(): string {
		return '_yoast_wpseo_metadesc';
	}

	protected function target_type(): string {
		return 'post';
	}
}
