<?php
/**
 * Fix method: image_alt.
 *
 * Sets the WP attachment alt text (_wp_attachment_image_alt). Suggested string
 * is generated by the Seonix backend.
 *
 * Accepts EITHER:
 *   - image_url  (preferred — what the scanner emits)
 *   - post_id    (the attachment's WP id, if the caller already resolved it)
 *
 * Pages typically host multiple images, and the scanner reports the page URL
 * as issue.url with the missing-alt image URLs in details.image_urls. So the
 * fix item carries an image URL, and we resolve it to an attachment id at
 * apply time via attachment_url_to_postid().
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Seonix_Fix_Image_Alt extends Seonix_Fix_Single_Meta {

	public function key(): string {
		return 'image_alt';
	}

	protected function meta_key(): string {
		return '_wp_attachment_image_alt';
	}

	protected function target_type(): string {
		return 'attachment';
	}

	public function validate_params( array $params ) {
		// Accept image_url as the canonical input; only require post_id when
		// no URL is given.
		$has_url     = ! empty( $params['image_url'] ) && is_string( $params['image_url'] );
		$has_post_id = isset( $params['post_id'] ) && is_numeric( $params['post_id'] ) && (int) $params['post_id'] > 0;

		if ( ! $has_url && ! $has_post_id ) {
			return new WP_Error(
				'missing_target',
				'image_alt needs either image_url or post_id (attachment id).',
				array( 'status' => 400 )
			);
		}
		if ( ! array_key_exists( 'suggested_value', $params ) || ! is_string( $params['suggested_value'] ) ) {
			return new WP_Error(
				'missing_suggested_value',
				'suggested_value is required and must be a string.',
				array( 'status' => 400 )
			);
		}
		return true;
	}

	public function dry_run( array $params ) {
		$post_id = $this->resolve_attachment_id( $params );
		if ( $post_id instanceof WP_Error ) {
			return $post_id;
		}
		// Hand off to base with the resolved id.
		$params['post_id'] = $post_id;
		return parent::dry_run( $params );
	}

	public function apply( array $params ) {
		$post_id = $this->resolve_attachment_id( $params );
		if ( $post_id instanceof WP_Error ) {
			return $post_id;
		}
		$image_url = isset( $params['image_url'] ) ? (string) $params['image_url'] : '';
		$suggested = isset( $params['suggested_value'] ) ? (string) $params['suggested_value'] : '';

		// Step 1: write attachment meta. This is the WP "default" alt for new
		// blocks that reference this attachment going forward.
		$params['post_id'] = $post_id;
		$result = parent::apply( $params );
		if ( $result instanceof WP_Error ) {
			return $result;
		}

		// Step 2: also rewrite empty alt="" in posts that already render this
		// image, because Gutenberg + page builders (UAGB, Astra) bake the alt
		// attribute into post_content at insert time. Without this step the
		// SEO scanner keeps reporting images_missing_alt — the attachment is
		// fine but the rendered HTML still has alt="".
		if ( '' !== $image_url && '' !== $suggested ) {
			$rewrite = $this->rewrite_alt_in_posts( $image_url, $suggested );
			if ( is_array( $result ) && ! empty( $rewrite ) ) {
				// Persist the affected post ids UNDER after_state (the controller
				// records before/after only, so a top-level key would be lost) so
				// rollback() can find those posts and surgically revert the alt we
				// wrote — no page copies needed.
				$result['after']['post_rewrites']      = $rewrite;
				$result['after']['post_rewrite_count'] = array_sum( $rewrite );
				// We changed real post_content, so this run is 'applied', not
				// 'already_applied', even if the attachment meta was already set.
				$result['no_op'] = false;
			}
		}

		return $result;
	}

	/**
	 * Undo an image_alt fix SURGICALLY.
	 *
	 * Step 1 — restore the attachment meta from the single stored value (the
	 * base class handles this; it is one short string, not a page copy).
	 *
	 * Step 2 — for every post the fix rewrote (recorded in
	 * after_state['post_rewrites']), reverse the alt we wrote back to empty on
	 * the CURRENT content, and ONLY where the alt is still exactly the value we
	 * set. A post whose alt an editor changed since, or that no longer contains
	 * the image, is left untouched — we never restore a stored page copy, so
	 * unrelated edits survive.
	 */
	public function rollback( int $history_id ) {
		$meta_result = parent::rollback( $history_id );
		if ( $meta_result instanceof WP_Error ) {
			return $meta_result;
		}

		$entry     = $this->history->get( $history_id );
		$params    = ( is_array( $entry ) && isset( $entry['params'] ) && is_array( $entry['params'] ) ) ? $entry['params'] : array();
		$image_url = isset( $params['image_url'] ) ? (string) $params['image_url'] : '';
		$alt       = isset( $params['suggested_value'] ) ? (string) $params['suggested_value'] : '';

		$reverted = 0;
		$rewrites = ( is_array( $entry ) && isset( $entry['after_state']['post_rewrites'] ) && is_array( $entry['after_state']['post_rewrites'] ) )
			? $entry['after_state']['post_rewrites']
			: array();

		if ( '' !== $image_url && '' !== $alt && ! empty( $rewrites ) ) {
			foreach ( array_keys( $rewrites ) as $raw_id ) {
				$post_id = (int) $raw_id;
				if ( $post_id <= 0 ) {
					continue;
				}
				$post = get_post( $post_id );
				if ( ! $post ) {
					continue;
				}
				$count       = 0;
				$new_content = $this->revert_alt_in_html( (string) $post->post_content, $image_url, $alt, $count );
				if ( $count > 0 && $new_content !== $post->post_content ) {
					$ok = wp_update_post( array(
						'ID'           => (int) $post_id,
						// wp_slash: content is DB-read; wp_update_post() unslashes.
						'post_content' => wp_slash( $new_content ),
					), true );
					if ( ! ( $ok instanceof WP_Error ) && (int) $ok > 0 ) {
						$reverted++;
					}
				}
			}
		}

		if ( is_array( $meta_result ) ) {
			$meta_result['reverted_posts'] = $reverted;
		}
		return $meta_result;
	}

	/**
	 * Find posts whose post_content references this image URL and rewrite the
	 * empty alt attribute on its <img> tag(s) to the suggested value. We only
	 * touch tags that currently have alt="" — images with a non-empty alt are
	 * left alone so we never overwrite an editor's deliberate caption.
	 *
	 * @return array<int,int>  map of post_id → number of <img> tags updated
	 */
	private function rewrite_alt_in_posts( string $image_url, string $alt ): array {
		global $wpdb;
		if ( ! $wpdb || empty( $wpdb->posts ) ) {
			return array();
		}
		// Direct DB lookup: WP_Query+meta won't help here, the image URL
		// lives in post_content. LIKE on the path is enough — the URL is
		// long and unique.
		$path = $this->path_only( $image_url );
		if ( '' === $path ) {
			return array();
		}
		$like = '%' . $wpdb->esc_like( $path ) . '%';
		// LIKE-on-post_content scan: WP_Query has no efficient analog, and a
		// one-shot SEO-fix dispatch has no useful caching opportunity.
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery,WordPress.DB.DirectDatabaseQuery.NoCaching
		$rows = $wpdb->get_results( $wpdb->prepare(
			"SELECT ID, post_content FROM {$wpdb->posts} WHERE post_content LIKE %s AND post_status IN ('publish','draft','pending') LIMIT 200",
			$like
		) );
		if ( empty( $rows ) ) {
			return array();
		}

		$updates = array();
		foreach ( $rows as $row ) {
			$new_content = $this->rewrite_alt_in_html( $row->post_content, $image_url, $alt, $count );
			if ( $count > 0 && $new_content !== $row->post_content ) {
				$ok = wp_update_post( array(
					'ID'           => (int) $row->ID,
					// wp_slash: $new_content is the DB-read post_content with alt
					// attributes rewritten; wp_update_post() unslashes its input,
					// so re-slash to keep literal backslashes intact.
					'post_content' => wp_slash( $new_content ),
				), true );
				if ( ! ( $ok instanceof WP_Error ) && (int) $ok > 0 ) {
					$updates[ (int) $row->ID ] = $count;
				}
			}
		}
		return $updates;
	}

	/**
	 * Replace alt="" with alt="{escaped}" inside any place this image is
	 * referenced in the post content. Sets $count to the total number of
	 * rewrites.
	 *
	 * Two passes:
	 *   1. <img> tags — covers Gutenberg core/image and most page-builder
	 *      blocks that render <img> directly into post_content.
	 *   2. Block-attribute JSON — covers Spectra/UAGB image gallery + swiper
	 *      carousel + similar where the URL lives in a JSON object inside an
	 *      HTML comment ({"id":N,"url":"...","alt":""}). One swiper block on
	 *      a reusable wp_block can contain 28 of these.
	 *
	 * Tags / objects with non-empty alt are preserved — we never overwrite an
	 * editor-supplied caption.
	 */
	private function rewrite_alt_in_html( string $html, string $image_url, string $alt, &$count ): string {
		$count = 0;
		$base  = preg_quote( $this->basename_no_ext( $image_url ), '~' );
		if ( '' === $base ) {
			return $html;
		}

		// Pass 1: <img> tags with empty alt.
		$alt_escaped_html = htmlspecialchars( $alt, ENT_QUOTES, 'UTF-8' );
		$tag_pattern = '~(<img\b[^>]*?(?:src|data-src)=["\'][^"\']*' . $base . '[^"\']*["\'][^>]*?\balt=)(["\'])(\2)~i';
		$html = preg_replace_callback( $tag_pattern, function ( $m ) use ( $alt_escaped_html, &$count ) {
			$count++;
			return $m[1] . '"' . $alt_escaped_html . '"';
		}, $html );
		if ( ! is_string( $html ) ) {
			return '';
		}

		// Pass 2: Block-JSON empty-alt instances near our image's basename.
		//
		// Spectra/UAGB mediaGallery items wrap a nested "sizes":{thumbnail,
		// medium, large, full} object before the alt field, so a flat
		// [^{}]*? regex over the enclosing braces never matches. Instead we
		// walk every "alt":"" occurrence and check a window around it for the
		// matching basename URL — same outcome, no nested-brace headaches.
		$alt_json_inner = trim( (string) wp_json_encode( $alt, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ), '"' );
		$replacement    = '"alt":"' . $alt_json_inner . '"';
		$base_re        = '~' . $base . '~i';

		$html = $this->rewrite_block_json_alt( $html, $base_re, $replacement, $count );

		return $html;
	}

	/**
	 * Inverse of rewrite_alt_in_html: put the alt we wrote back to empty, but
	 * ONLY where it is still exactly the value we set — so a caption an editor
	 * changed after the fix is never clobbered. Sets $count to the number of
	 * reverts. Used by rollback().
	 */
	private function revert_alt_in_html( string $html, string $image_url, string $alt, &$count ): string {
		$count = 0;
		$base  = preg_quote( $this->basename_no_ext( $image_url ), '~' );
		if ( '' === $base || '' === $alt ) {
			return $html;
		}

		// Pass 1: <img> tags whose alt is exactly our value → back to alt="".
		$alt_escaped_html = htmlspecialchars( $alt, ENT_QUOTES, 'UTF-8' );
		$alt_q            = preg_quote( $alt_escaped_html, '~' );
		$tag_pattern      = '~(<img\b[^>]*?(?:src|data-src)=["\'][^"\']*' . $base . '[^"\']*["\'][^>]*?\balt=)"' . $alt_q . '"~i';
		$html             = preg_replace_callback( $tag_pattern, function ( $m ) use ( &$count ) {
			$count++;
			return $m[1] . '""';
		}, $html );
		if ( ! is_string( $html ) ) {
			return '';
		}

		// Pass 2: block-JSON "alt":"<our value>" → "alt":"" within objects that
		// reference this image.
		$alt_json_inner = trim( (string) wp_json_encode( $alt, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES ), '"' );
		$needle         = '"alt":"' . $alt_json_inner . '"';
		$base_re        = '~' . $base . '~i';

		$html = $this->walk_block_json_alt( $html, $needle, '"alt":""', $base_re, $count );

		return $html;
	}

	/**
	 * Walk every "alt":"" in the content, find the enclosing {…} object via
	 * brace-counting, and rewrite if the basename URL appears anywhere inside
	 * that object (including arbitrarily nested children — which is the case
	 * for Spectra mediaGallery items where the URL lives in a "sizes" subtree
	 * sibling to "alt").
	 *
	 * Brace counting handles nesting correctly. JSON strings can technically
	 * contain literal { and } (they're not escaped) — but block-attribute JSON
	 * never does, so a simpler counter is fine in practice.
	 */
	private function rewrite_block_json_alt( string $html, string $base_re, string $replacement, int &$count ): string {
		return $this->walk_block_json_alt( $html, '"alt":""', $replacement, $base_re, $count );
	}

	/**
	 * Walk every $needle occurrence, find its enclosing {…} object via
	 * brace-counting, and swap it for $replacement when that object references
	 * this image's basename ($base_re). Shared by the forward rewrite (needle
	 * "alt":"") and the rollback revert (needle "alt":"<our value>").
	 */
	private function walk_block_json_alt( string $html, string $needle, string $replacement, string $base_re, int &$count ): string {
		$needle_len = strlen( $needle );
		$out        = '';
		$cursor     = 0;
		$len        = strlen( $html );

		while ( $cursor < $len ) {
			$pos = strpos( $html, $needle, $cursor );
			if ( false === $pos ) {
				$out .= substr( $html, $cursor );
				break;
			}

			$out .= substr( $html, $cursor, $pos - $cursor );

			$open  = $this->find_enclosing_object_open( $html, $pos );
			$close = $open >= 0 ? $this->find_matching_object_close( $html, $open ) : -1;
			$inside_match = false;
			if ( $open >= 0 && $close > $pos ) {
				$slice = substr( $html, $open, $close - $open + 1 );
				if ( preg_match( $base_re, $slice ) ) {
					$inside_match = true;
				}
			}

			if ( $inside_match ) {
				$out .= $replacement;
				$count++;
			} else {
				$out .= $needle;
			}
			$cursor = $pos + $needle_len;
		}
		return $out;
	}

	/**
	 * Walk backwards from $alt_pos to find the {[index] of the immediately
	 * enclosing object. Returns -1 if none found within the buffer.
	 */
	private function find_enclosing_object_open( string $s, int $alt_pos ): int {
		$depth = 0;
		for ( $i = $alt_pos - 1; $i >= 0; $i-- ) {
			$c = $s[ $i ];
			if ( '}' === $c ) {
				$depth++;
			} elseif ( '{' === $c ) {
				if ( 0 === $depth ) {
					return $i;
				}
				$depth--;
			}
		}
		return -1;
	}

	/**
	 * From an opening brace position, walk forward to find its matching close.
	 */
	private function find_matching_object_close( string $s, int $open_pos ): int {
		$depth = 0;
		$len   = strlen( $s );
		for ( $i = $open_pos; $i < $len; $i++ ) {
			$c = $s[ $i ];
			if ( '{' === $c ) {
				$depth++;
			} elseif ( '}' === $c ) {
				$depth--;
				if ( 0 === $depth ) {
					return $i;
				}
			}
		}
		return -1;
	}

	private function path_only( string $url ): string {
		$p = wp_parse_url( $url, PHP_URL_PATH );
		return is_string( $p ) ? $p : '';
	}

	private function basename_no_ext( string $url ): string {
		$path = $this->path_only( $url );
		$base = basename( $path );
		if ( '' === $base ) {
			return '';
		}
		// Strip extension AND -WIDTHxHEIGHT suffix to match all variants.
		if ( false !== ( $dot = strrpos( $base, '.' ) ) ) {
			$base = substr( $base, 0, $dot );
		}
		return preg_replace( '/-\d+x\d+$/', '', $base );
	}

	/**
	 * @return int|\WP_Error attachment ID, or error if unresolvable.
	 */
	private function resolve_attachment_id( array $params ) {
		// Explicit post_id wins.
		if ( ! empty( $params['post_id'] ) && is_numeric( $params['post_id'] ) ) {
			$id = (int) $params['post_id'];
			if ( $id > 0 ) {
				return $id;
			}
		}

		$image_url = isset( $params['image_url'] ) ? (string) $params['image_url'] : '';
		if ( '' === $image_url ) {
			return new WP_Error( 'missing_target', 'No image_url or post_id provided.', array( 'status' => 400 ) );
		}

		if ( ! function_exists( 'attachment_url_to_postid' ) ) {
			return new WP_Error( 'wp_unavailable', 'attachment_url_to_postid is not available.', array( 'status' => 500 ) );
		}

		// Try in order of strictness — first the URL as given, then a few
		// normalisation passes. Each normalisation handles a real failure
		// mode seen in production:
		//   urldecoded:  filenames with Cyrillic / spaces ("18-мая-2025") arrive
		//                URL-encoded; WP's DB stores them decoded.
		//   sized:       <img src> uses scaled variant (-300x200); attachment
		//                row lives at the original.
		//   urldecoded + sized: both at once.
		$candidates = array_unique( array_filter( array(
			$image_url,
			urldecode( $image_url ),
			$this->strip_size_suffix( $image_url ),
			$this->strip_size_suffix( urldecode( $image_url ) ),
		) ) );

		foreach ( $candidates as $url ) {
			$id = (int) attachment_url_to_postid( $url );
			if ( $id > 0 ) {
				return $id;
			}
		}

		return new WP_Error(
			'attachment_not_found',
			sprintf( 'No attachment matches URL: %s', $image_url ),
			array( 'status' => 404 )
		);
	}

	/**
	 * Strip the "-WIDTHxHEIGHT" suffix WP appends to scaled image URLs so we
	 * can match the original upload's attachment row. Touches only the path's
	 * basename — leaves the host and directory untouched.
	 */
	private function strip_size_suffix( string $url ): string {
		$parts = wp_parse_url( $url );
		if ( empty( $parts['path'] ) ) {
			return $url;
		}
		$path = $parts['path'];
		$base = basename( $path );
		$ext  = '';
		if ( false !== ( $dot = strrpos( $base, '.' ) ) ) {
			$ext  = substr( $base, $dot );
			$base = substr( $base, 0, $dot );
		}
		$cleaned = preg_replace( '/-\d+x\d+$/', '', $base );
		if ( $cleaned === $base ) {
			return $url;
		}
		$new_path  = dirname( $path ) . '/' . $cleaned . $ext;
		$rebuilt   = ( $parts['scheme'] ?? 'https' ) . '://' . ( $parts['host'] ?? '' ) . $new_path;
		if ( ! empty( $parts['query'] ) ) {
			$rebuilt .= '?' . $parts['query'];
		}
		return $rebuilt;
	}
}
