<?php
/**
 * Shared base for fix methods whose job is "set one post-meta key to a value".
 *
 * Concrete methods (meta_title, meta_description, image_alt) only need to declare
 * which meta key they own and what the target_type is. Validation, dry-run/apply
 * idempotency, and rollback live here.
 *
 * The "suggested_value" is generated by the Seonix backend (AI for image alts
 * and meta texts) and arrives as a plain string in params. The plugin is just
 * the executor — it never invents content on its own.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

abstract class Seonix_Fix_Single_Meta implements Seonix_Fix_Method {

	protected Seonix_SEO_Fix_History $history;

	public function __construct( Seonix_SEO_Fix_History $history ) {
		$this->history = $history;
	}

	abstract public function key(): string;
	abstract protected function meta_key(): string;
	abstract protected function target_type(): string;

	/**
	 * Resolve the meta key to read/write for this run, or a WP_Error when the
	 * fix can't run in the current environment. Defaults to the static
	 * meta_key().
	 *
	 * @return string|\WP_Error
	 */
	protected function resolve_meta_key() {
		return $this->meta_key();
	}

	/**
	 * When non-null, this fix reads/writes through the SEO meta bridge
	 * (Seonix canonical keys + every active engine incl. AIOSEO's table)
	 * instead of a single postmeta key. Returns the bridge field name
	 * ('seo_title' | 'meta_description'). meta_title / meta_description
	 * override this; image_alt keeps the plain single-key path.
	 *
	 * @return string|null
	 */
	protected function bridge_field(): ?string {
		return null;
	}

	/**
	 * Current effective value of the bridge field (primary engine first,
	 * Seonix canonical store as fallback).
	 */
	private function bridge_current( int $post_id, string $field ): string {
		$effective = Seonix_Meta_Bridge::read_effective( $post_id );
		return isset( $effective[ $field ] ) ? (string) $effective[ $field ] : '';
	}

	public function validate_params( array $params ) {
		if ( empty( $params['post_id'] ) || ! is_numeric( $params['post_id'] ) ) {
			return new WP_Error( 'missing_post_id', 'post_id is required.', array( 'status' => 400 ) );
		}
		if ( ! array_key_exists( 'suggested_value', $params ) || ! is_string( $params['suggested_value'] ) ) {
			return new WP_Error( 'missing_suggested_value', 'suggested_value is required and must be a string.', array( 'status' => 400 ) );
		}
		return true;
	}

	public function dry_run( array $params ) {
		$post_id = (int) $params['post_id'];
		$field   = $this->bridge_field();
		if ( null !== $field ) {
			$current = $this->bridge_current( $post_id, $field );
		} else {
			$key = $this->resolve_meta_key();
			if ( is_wp_error( $key ) ) {
				return $key;
			}
			$current = (string) get_post_meta( $post_id, $key, true );
		}
		return $this->describe_result( $post_id, $current, (string) $params['suggested_value'] );
	}

	public function apply( array $params ) {
		$post_id   = (int) $params['post_id'];
		$field     = $this->bridge_field();
		$suggested = (string) $params['suggested_value'];

		if ( null !== $field ) {
			$current = $this->bridge_current( $post_id, $field );
		} else {
			$key = $this->resolve_meta_key();
			if ( is_wp_error( $key ) ) {
				return $key;
			}
			$current = (string) get_post_meta( $post_id, $key, true );
		}

		// Safety guard: never overwrite an existing non-empty meta value with an
		// empty one. The backend translator emits suggested_value='' for items
		// pending an AI suggestion; without this check those items would silently
		// wipe the SEO plugin's titles/descriptions when an unfilled run is
		// applied.
		if ( '' === $suggested && '' !== $current ) {
			return new WP_Error(
				'refuse_overwrite_empty',
				'Refusing to overwrite an existing meta value with an empty suggestion. Fill suggested_value before applying.',
				array( 'status' => 422 )
			);
		}

		$result = $this->describe_result( $post_id, $current, $suggested );

		if ( $result['no_op'] ) {
			return $result;
		}

		if ( null !== $field ) {
			// Bridge path: writes Seonix's canonical keys + every active engine
			// (Yoast/RM/SEOPress/TSF postmeta, AIOSEO via its model). With no
			// SEO plugin at all, the standalone renderer serves the value.
			Seonix_Meta_Bridge::write( $post_id, array( $field => $suggested ) );
			return $result;
		}

		// wp_slash: update_post_meta() runs wp_unslash() on the value, and the
		// controller already wp_unslash()ed the incoming REST params, so re-slash
		// here or a title/description containing a backslash is silently mangled.
		$ok = update_post_meta( $post_id, $this->resolve_meta_key(), wp_slash( $suggested ) );
		if ( false === $ok ) {
			return new WP_Error( 'update_failed', 'update_post_meta returned false.', array( 'status' => 500 ) );
		}
		return $result;
	}

	public function rollback( int $history_id ) {
		$entry = $this->history->get( $history_id );
		if ( ! $entry ) {
			return new WP_Error( 'unknown_history_entry', 'No history entry with that id.', array( 'status' => 404 ) );
		}

		$post_id  = (int) ( $entry['target_id'] ?? 0 );
		$old_val  = $entry['before_state']['value'] ?? null;

		if ( $post_id <= 0 || ! is_string( $old_val ) ) {
			return new WP_Error( 'invalid_history_entry', 'History entry is missing snapshot.', array( 'status' => 422 ) );
		}

		$field = $this->bridge_field();
		if ( null !== $field ) {
			// Restore the previous value everywhere the apply wrote it.
			Seonix_Meta_Bridge::write( $post_id, array( $field => $old_val ) );
			return array(
				'before' => array( 'value' => (string) ( $entry['after_state']['value'] ?? '' ) ),
				'after'  => array( 'value' => $old_val ),
			);
		}

		$key = $this->resolve_meta_key();
		if ( is_wp_error( $key ) ) {
			return $key;
		}

		// wp_slash: restore the unslashed snapshot slashed so update_post_meta's
		// internal wp_unslash round-trips it back to the original value.
		update_post_meta( $post_id, $key, wp_slash( $old_val ) );

		return array(
			'before' => array( 'value' => (string) ( $entry['after_state']['value'] ?? '' ) ),
			'after'  => array( 'value' => $old_val ),
		);
	}

	private function describe_result( int $post_id, string $current, string $suggested ): array {
		$is_no_op = $current === $suggested;

		// `diff` dropped in 2.2.5: controller no longer ships it on the wire.
		// The truncate helper is retained as a future-proof utility but is
		// currently unused on this method.
		return array(
			'before' => array( 'value' => $current ),
			'after'  => array( 'value' => $suggested ),
			'no_op'  => $is_no_op,
			'target' => array(
				'type' => $this->target_type(),
				'id'   => $post_id,
			),
		);
	}

	private function truncate( string $s, int $max = 80 ): string {
		return mb_strlen( $s ) > $max ? mb_substr( $s, 0, $max - 1 ) . '…' : $s;
	}
}
