<?php
/**
 * Fix method: meta_description.
 *
 * Sets the meta description through the meta bridge: Seonix's canonical
 * `_seonix_meta_description` plus every active SEO plugin's storage (Yoast /
 * Rank Math / SEOPress / TSF postmeta, AIOSEO via its Post model). With no
 * SEO plugin installed the standalone meta renderer serves the value, so the
 * fix works on every site. Suggested string is generated by the Seonix
 * backend (AI-summarised from page content, length-bounded to 50–160).
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Seonix_Fix_Meta_Description extends Seonix_Fix_Single_Meta {

	public function key(): string {
		return 'meta_description';
	}

	/**
	 * Static fallback (the abstract contract). Reads/writes actually go
	 * through the bridge — see bridge_field().
	 */
	protected function meta_key(): string {
		$key = Seonix_SEO_Engine::post_desc_key();
		return null !== $key ? $key : Seonix_Meta_Bridge::META_DESC;
	}

	protected function target_type(): string {
		return 'post';
	}

	protected function bridge_field(): ?string {
		return 'meta_description';
	}

	/**
	 * Advertised to the /capabilities handshake. Available whenever the value
	 * will actually reach the page: a postmeta engine is active, AIOSEO's
	 * model is writable, or Seonix itself renders the head meta (no SEO
	 * plugin + mode allows output). An unsupported SEO plugin owning <head>
	 * (e.g. Squirrly) stays gated off so we never claim a fix that can't take
	 * effect.
	 */
	public function is_available(): bool {
		if ( null !== Seonix_SEO_Engine::post_desc_key() ) {
			return true;
		}
		if ( class_exists( '\AIOSEO\Plugin\Common\Models\Post' ) ) {
			return true;
		}
		return Seonix_Meta_Renderer::should_output();
	}
}
